Adds magic types from fantasy novels and games
Lingwars/todosloscorpus pull request #31
Opened 2020-11-01 19:00 UTC by Alberdi

2020-11-01 19:13 UTC, xurxodiz requested changes

2020-11-01 19:13 UTC, xurxodiz commented on data/games/fantasy_magics.json
> +				"name": "maetmágico",
*matemágico

2020-11-01 19:35 UTC, xurxodiz requested changes

2020-11-01 19:35 UTC, xurxodiz commented on data/games/fantasy_magics.json
> +				"name": "maetmágico",
```suggestion
				"name": "matemágico",
```

2020-11-02 11:31 UTC, xurxodiz requested changes

2020-11-02 11:31 UTC, xurxodiz commented on data/games/fantasy_magics.json
> +			"gender": "l",
```suggestion
			"gender": "f",
```

2020-11-02 11:31 UTC, xurxodiz commented on data/games/fantasy_magics.json
> +			"gender": "l",
```suggestion
			"gender": "f",
```

2020-11-02 11:45 UTC, Alberdi commented on data/games/fantasy_magics.json
> +			"gender": "l",
😞

2020-11-02 11:51 UTC, xurxodiz approved these changes

2020-11-02 11:51 UTC, merged