Adds Spanish wines
Lingwars/todosloscorpus pull request #47
Opened 2020-11-04 12:37 UTC by xurxodiz

2020-11-06 20:33 UTC, nimbusaeta commented on data/foods/spanish_wines.json
> +			"area": "Araba/Álava",
¿Qué tal solo "Araba"? Ya que en el resto del fichero parece que estamos usando los nombres autóctonos...

2020-11-06 20:34 UTC, nimbusaeta commented on data/foods/spanish_wines.json
> +			"area": "Ríaas Baixas",
Typo en Ríaas

2020-11-06 20:34 UTC, xurxodiz commented on data/foods/spanish_wines.json
> +			"area": "Araba/Álava",
Nombres oficiales, es el criterio que usé.

2020-11-06 20:34 UTC, nimbusaeta commented on data/foods/spanish_wines.json
> +			"area": "Arganda del Rey/Navalcarnero/San Martin de Valdeiglesias/El Molar",
Martín

2020-11-06 20:35 UTC, nimbusaeta requested changes
Gracias! Hay 3 cosillas en las que podría mejorar :)

2020-11-06 20:36 UTC, nimbusaeta commented on data/foods/spanish_wines.json
> +			"area": "Araba/Álava",
Ahhhh ok

2020-11-08 13:12 UTC, xurxodiz commented on data/foods/spanish_wines.json
> +			"area": "Ríaas Baixas",
```suggestion
			"area": "Rías Baixas",
```

2020-11-08 13:12 UTC, xurxodiz commented on data/foods/spanish_wines.json
> +			"area": "Arganda del Rey/Navalcarnero/San Martin de Valdeiglesias/El Molar",
```suggestion
			"area": "Arganda del Rey/Navalcarnero/San Martín de Valdeiglesias/El Molar",
```

2020-11-08 13:20 UTC, xurxodiz commented
Creo que así ya está :)

2020-11-09 13:19 UTC, nimbusaeta commented
Gracias, Xurxo!

2020-11-09 13:19 UTC, merged